amountOfMoney:
    amount: '%amount%'
    currencyCode: '%currency%'
customer:
    address:
        countryCode: '%country%'
        name:
            firstName: '%first_name%'
            surname: '%last_name%'
refundReferences:
    merchantReference: '%order_id%'
