<?php

namespace SmashPig\PaymentProviders\Adyen;

use SmashPig\Core\Helpers\CurrencyRoundingHelper;

/**
 * Overrides the parent class for currencies marked as 'differs from standard'
 * at https://docs.adyen.com/development-resources/currency-codes/
 */
class AdyenCurrencyRoundingHelper extends CurrencyRoundingHelper {

	public static function isFractionalCurrency( string $currencyCode ): bool {
		switch ( $currencyCode ) {
			case 'CLP':
			case 'ISK':
				return true;
			case 'CVE':
			case 'IDR':
				return false;
			default:
				return parent::isFractionalCurrency( $currencyCode ); // TODO: Change the autogenerated stub
		}
	}
}
