#
# this file provides configuration for Travis Continuous Integration
# written by Sam-Mauris Yong
#

language: php

dist: trusty
 
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 5.3
      dist: precise
    - php: 7.0
    - php: hhvm

mysql:
  database: phpqueuetest
  username: root
  encoding: utf8

before_install: echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - mysql -e 'create database phpqueuetest;'
  - composer self-update
  - composer install --no-dev

script: phpunit --coverage-text -c phpunit.travis.xml

