<?php

namespace SmashPig\PaymentProviders\Chariot\Audit;

use SmashPig\Core\DataFiles\AuditParser;
use SmashPig\Core\Helpers\CurrencyRoundingHelper;
use SmashPig\Core\UtcDate;

// Parser for Chariot donations audit CSV files generated by
// PaymentProviders/Chariot/Maintenance/GetReport.php.
class DonationsAudit implements AuditParser {

	public function parseFile( string $path ): array {
		$handle = fopen( $path, 'r' );
		if ( !$handle ) {
			throw new \RuntimeException( 'Unable to open file ' . $path );
		}

		$headers = fgetcsv( $handle, 0, ',', '"', '\\' );
		if ( !$headers ) {
			fclose( $handle );
			return [];
		}

		$output = [];
		while ( ( $row = fgetcsv( $handle, 0, ',', '"', '\\' ) ) !== false ) {
			if ( count( $row ) === 1 && trim( (string)$row[0] ) === '' ) {
				continue;
			}
			$combined = [];
			foreach ( $headers as $index => $header ) {
				$combined[$header] = $row[$index] ?? '';
			}
			$output[] = $this->normalizeRow( $combined );
		}

		fclose( $handle );
		return $output;
	}

	private function normalizeRow( array $row ): array {
		$msg = [
			'gateway' => 'chariot',
			'audit_file_gateway' => 'chariot',
			'type' => $row['type'] ?: 'donation',
			'gift_source' => $row['gift_source'] ?: '',
			'direct_mail_appeal' => $row['direct_mail_appeal'] ?: '',
			'date' => $this->toUtcTimestamp( $row['date'] ?? null ),
			'settled_date' => $this->toUtcTimestamp( $row['settled_date'] ?? null ),
			'gateway_txn_id' => $row['gateway_txn_id'],
			'backend_processor' => $row['backend_processor'],
			'backend_processor_txn_id' => $row['backend_processor_txn_id'],
			'banking_institution' => $row['banking_institution'],
			'matching_gift_organization' => $row['matching_gift_organization'],
			'payment_method' => $row['payment_method'],
			'exchange_rate' => $row['exchange_rate'],
			'original_total_amount' => $row['original_total_amount'],
			'original_fee_amount' => $row['original_fee_amount'],
			'original_net_amount' => $row['original_net_amount'],
			'original_matching_gift_total_amount' => $row['original_matching_gift_total_amount'],
			'original_matching_gift_fee_amount' => $row['original_matching_gift_fee_amount'],
			'original_matching_gift_net_amount' => $row['original_matching_gift_net_amount'],
			'original_individual_gift_total_amount' => $row['original_individual_gift_total_amount'],
			'original_individual_gift_fee_amount' => $row['original_individual_gift_fee_amount'],
			'original_individual_gift_net_amount' => $row['original_individual_gift_net_amount'],
			'original_currency' => $row['original_currency'],
			'settled_total_amount' => $row['settled_total_amount'],
			'settled_fee_amount' => $row['settled_fee_amount'],
			'settled_net_amount' => $row['settled_net_amount'],
			'settled_matching_gift_total_amount' => $row['settled_matching_gift_total_amount'],
			'settled_matching_gift_fee_amount' => $row['settled_matching_gift_fee_amount'],
			'settled_matching_gift_net_amount' => $row['settled_matching_gift_net_amount'],
			'settled_individual_gift_total_amount' => $row['settled_individual_gift_total_amount'],
			'settled_individual_gift_fee_amount' => $row['settled_individual_gift_fee_amount'],
			'settled_individual_gift_net_amount' => $row['settled_individual_gift_net_amount'],
			'settled_currency' => $row['settled_currency'],
			'settlement_batch_reference' => $row['settlement_batch_reference'],
			'full_name' => $row['full_name'],
			'first_name' => $row['first_name'],
			'last_name' => $row['last_name'],
			'partner_full_name' => $row['partner_full_name'],
			'prefix' => $row['prefix'],
			'email' => $row['email'],
			'phone' => $row['phone'],
			'donor_advised_fund_name' => $row['donor_advised_fund_name'],
			'is_daf' => $row['is_daf'],
			'is_matching_gift' => $row['is_matching_gift'],
			'note' => $row['note'],
			'street_address' => $row['street_address'],
			'supplemental_address_1' => $row['supplemental_address_1'],
			'city' => $row['city'],
			'state_province' => $row['state_province'],
			'postal_code' => $row['postal_code'],
			'country' => $row['country'],
			'manual_review' => $row['is_endowment'] ? 'endowment' : false,
			'check_number' => $row['check_number'],
		];
		$this->validateAmounts( $msg );

		return array_filter( $msg, static fn ( $value ) => $value !== null && $value !== '' );
	}

	private function validateAmounts( array $msg ): void {
		$this->assertAmountsEqual(
			$msg['original_net_amount'] ?: '0.00',
			[
				$msg['original_total_amount'] ?: '0.00',
				$msg['original_fee_amount'] ?: '0.00',
			],
			$msg['original_currency'],
			'Original total + fee must equal net'
		);

		if (
			!empty( $msg['original_individual_gift_total_amount'] ) ||
			!empty( $msg['original_matching_gift_total_amount'] )
		) {
			$this->assertAmountsEqual(
				$msg['original_total_amount'] ?: '0.00',
				[
					$msg['original_individual_gift_total_amount'] ?? '0.00',
					$msg['original_matching_gift_total_amount'] ?? '0.00',
				],
				$msg['original_currency'],
				'Original individual + matching totals must equal total'
			);

			$this->assertAmountsEqual(
				$msg['original_fee_amount'] ?? '0.00',
				[
					$msg['original_individual_gift_fee_amount'] ?? '0.00',
					$msg['original_matching_gift_fee_amount'] ?? '0.00',
				],
				$msg['original_currency'],
				'Original individual + matching fees must equal fee'
			);

			$this->assertAmountsEqual(
				$msg['original_net_amount'] ?: '0.00',
				[
					$msg['original_individual_gift_net_amount'] ?? '0.00',
					$msg['original_matching_gift_net_amount'] ?? '0.00',
				],
				$msg['original_currency'],
				'Original individual + matching net amounts must equal net'
			);
		}

		$this->assertAmountsEqual(
			$msg['settled_net_amount'] ?? '0.00',
			[
				$msg['settled_total_amount'] ?? '0.00',
				$msg['settled_fee_amount'] ?? '0.00',
			],
			$msg['settled_currency'],
			'Settled total + fee must equal net'
		);

		if (
			!empty( $msg['settled_individual_gift_total_amount'] ) ||
			!empty( $msg['settled_matching_gift_total_amount'] )
		) {
			$this->assertAmountsEqual(
				$msg['settled_total_amount'] ?? '0.00',
				[
					$msg['settled_individual_gift_total_amount'] ?? '0.00',
					$msg['settled_matching_gift_total_amount'] ?? '0.00',
				],
				$msg['settled_currency'],
				'Settled individual + matching totals must equal total'
			);

			$this->assertAmountsEqual(
				$msg['settled_fee_amount'] ?? '0.00',
				[
					$msg['settled_individual_gift_fee_amount'] ?? '0.00',
					$msg['settled_matching_gift_fee_amount'] ?? '0.00',
				],
				$msg['settled_currency'],
				'Settled individual + matching fees must equal fee'
			);

			$this->assertAmountsEqual(
				$msg['settled_net_amount'] ?? '0.00',
				[
					$msg['settled_individual_gift_net_amount'] ?? '0.00',
					$msg['settled_matching_gift_net_amount'] ?? '0.00',
				],
				$msg['settled_currency'],
				'Settled individual + matching net amounts must equal net'
			);
		}
	}

	private function assertAmountsEqual( string $sum, array $values, string $currency, string $description ): void {
		$actual = array_sum(
			array_map(
				fn ( $value ): int => $this->amountToMinorUnits( (string)$value, $currency ),
				$values
			)
		);

		$expected = $this->amountToMinorUnits( $sum, $currency );

		if ( $expected !== $actual ) {
			throw new \UnexpectedValueException(
				sprintf(
					'%s: expected %s, got %s',
					$description,
					$sum,
					$this->minorUnitsToAmount( $actual, $currency )
				)
			);
		}
	}

	private function amountToMinorUnits( string $amount, string $currency ): int {
		return CurrencyRoundingHelper::getAmountInMinorUnits( (float)$amount, $currency );
	}

	private function minorUnitsToAmount( float $minorUnits, string $currency ): string {
		return CurrencyRoundingHelper::getAmountInMajorUnits( $minorUnits, $currency );
	}

	private function toUtcTimestamp( ?string $value ): ?int {
		if ( $value === null || trim( $value ) === '' ) {
			return null;
		}
		return UtcDate::getUtcTimestamp( $value );
	}
}
