<?php

namespace SmashPig\PaymentProviders\Chariot\Audit;

use SmashPig\Core\DataFiles\AuditParser;
use SmashPig\Core\UtcDate;

// Parser for Chariot donations audit CSV files generated by
// PaymentProviders/Chariot/Maintenance/GetReport.php.
class DonationsAudit implements AuditParser {

	public function parseFile( string $path ): array {
		$handle = fopen( $path, 'r' );
		if ( !$handle ) {
			throw new \RuntimeException( 'Unable to open file ' . $path );
		}

		$headers = fgetcsv( $handle, 0, ',', '"', '\\' );
		if ( !$headers ) {
			fclose( $handle );
			return [];
		}

		$output = [];
		while ( ( $row = fgetcsv( $handle, 0, ',', '"', '\\' ) ) !== false ) {
			if ( count( $row ) === 1 && trim( (string)$row[0] ) === '' ) {
				continue;
			}
			$combined = [];
			foreach ( $headers as $index => $header ) {
				$combined[$header] = $row[$index] ?? '';
			}
			$output[] = $this->normalizeRow( $combined );
		}

		fclose( $handle );
		return $output;
	}

	private function normalizeRow( array $row ): array {
		$msg = [
			'gateway' => 'chariot',
			'audit_file_gateway' => 'chariot',
			'type' => $row['type'] ?: 'donation',
			'date' => $this->toUtcTimestamp( $row['date'] ?? null ),
			'settled_date' => $this->toUtcTimestamp( $row['settled_date'] ?? null ),
			'gateway_txn_id' => $row['gateway_txn_id'],
			'backend_processor' => $row['backend_processor'],
			'backend_processor_txn_id' => $row['backend_processor_txn_id'],
			'original_total_amount' => $row['original_total_amount'] ?: null,
			'original_currency' => $row['original_currency'] ?: null,
			'settled_total_amount' => $row['settled_total_amount'] ?: null,
			'settled_fee_amount' => $row['settled_fee_amount'] ?: null,
			'settled_net_amount' => $row['settled_net_amount'] ?: null,
			'settled_currency' => $row['settled_currency'] ?: null,
			'settlement_batch_reference' => $row['settlement_batch_reference'] ?: null,
			'full_name' => $row['donor_name'] ?? null,
			'first_name' => $row['donor_first_name'] ?? null,
			'last_name' => $row['last_name'] ?? null,
			'email' => $row['email'] ?? null,
			'phone' => $row['phone'] ?? null,
			'donor_advised_fund_name' => $row['donor_advised_fund_name'] ?? null,
			'purpose' => $row['purpose'] ?? null,
			'note' => $row['note'] ?: null,
			'match_amount' => $row['match_amount'] ?? '0.0',
			'daf_organization' => $row['daf_organization'] ?? null,
			'daf_program' => $row['daf_program'] ?? null,
			'street_address' => $row['donor_address_street'] ?? null,
			'supplemental_address_1' => $row['donor_address_street_2'] ?? null,
			'city' => $row['donor_address_city'] ?? null,
			'state' => $row['donor_address_state'] ?? null,
			'postal_code' => $row['donor_address_postal_code'] ?? null,
			'country' => $row['donor_address_country'] ?? null,
			'is_endowment' => $row['is_endowment'] ?? false,
		];

		return array_filter( $msg, static fn ( $value ) => $value !== null && $value !== '' );
	}

	private function firstNonEmpty( ?string ...$values ): ?string {
		foreach ( $values as $value ) {
			if ( $value !== null && trim( $value ) !== '' ) {
				return $value;
			}
		}
		return null;
	}

	private function toUtcTimestamp( ?string $value ): ?int {
		if ( $value === null || trim( $value ) === '' ) {
			return null;
		}
		return UtcDate::getUtcTimestamp( $value );
	}
}
