<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'ValueParsers\\' => array($vendorDir . '/data-values/number/src', $vendorDir . '/data-values/time/src'),
    'ValueFormatters\\' => array($vendorDir . '/data-values/number/src', $vendorDir . '/data-values/time/src'),
    'TextCat' => array($vendorDir . '/wikimedia/textcat'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Net' => array($vendorDir . '/pear/net_smtp', $vendorDir . '/pear/net_socket'),
    'Mail' => array($vendorDir . '/pear/mail', $vendorDir . '/pear/mail_mime'),
    'Liuggio' => array($vendorDir . '/liuggio/statsd-php-client/src'),
    'Less' => array($vendorDir . '/wikimedia/less.php/lib'),
    'Kafka\\' => array($vendorDir . '/nmred/kafka-php/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'DataValues\\' => array($vendorDir . '/data-values/number/src', $vendorDir . '/data-values/time/src'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    '' => array($vendorDir . '/cssjanus/cssjanus/src', $vendorDir . '/pear/pear-core-minimal/src'),
);
