<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'WrappedString\\' => array($vendorDir . '/wikimedia/wrappedstring/src'),
    'Wikimedia\\Purtle\\Tests\\' => array($vendorDir . '/wikimedia/purtle/tests/phpunit'),
    'Wikimedia\\Purtle\\' => array($vendorDir . '/wikimedia/purtle/src'),
    'Wikimedia\\Composer\\' => array($vendorDir . '/wikimedia/composer-merge-plugin/src'),
    'Wikimedia\\Assert\\Test\\' => array($vendorDir . '/wikimedia/assert/tests/phpunit'),
    'Wikimedia\\Assert\\' => array($vendorDir . '/wikimedia/assert/src'),
    'ValueValidators\\' => array($vendorDir . '/data-values/interfaces/src/ValueValidators'),
    'ValueParsers\\' => array($vendorDir . '/data-values/interfaces/src/ValueParsers', $vendorDir . '/data-values/common/src/ValueParsers'),
    'ValueFormatters\\' => array($vendorDir . '/data-values/interfaces/src/ValueFormatters', $vendorDir . '/data-values/common/src/ValueFormatters'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Serializers\\' => array($vendorDir . '/serialization/serialization/src/Serializers'),
    'RemexHtml\\' => array($vendorDir . '/wikimedia/remex-html/RemexHtml'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'JsonSchema\\' => array($vendorDir . '/justinrainbow/json-schema/src/JsonSchema'),
    'GDText\\' => array($vendorDir . '/stil/gd-text/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Elastica\\' => array($vendorDir . '/ruflin/elastica/lib/Elastica'),
    'Diff\\' => array($vendorDir . '/diff/diff/src'),
    'Deserializers\\' => array($vendorDir . '/serialization/serialization/src/Deserializers'),
    'DataValues\\Serializers\\' => array($vendorDir . '/data-values/serialization/src/Serializers'),
    'DataValues\\Geo\\' => array($vendorDir . '/data-values/geo/src'),
    'DataValues\\Deserializers\\' => array($vendorDir . '/data-values/serialization/src/Deserializers'),
    'DataValues\\' => array($vendorDir . '/data-values/common/src/DataValues'),
    'Composer\\Semver\\' => array($vendorDir . '/composer/semver/src'),
    'CLDRPluralRuleParser\\' => array($vendorDir . '/wikimedia/cldr-plural-rule-parser/src'),
);
