<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Liuggio' => array($vendorDir . '/liuggio/statsd-php-client/src'),
    '' => array($vendorDir . '/cssjanus/cssjanus/src', $vendorDir . '/kzykhys/pygments/src'),
);
