<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Wikimedia\\Composer\\' => array($vendorDir . '/wikimedia/composer-merge-plugin/src'),
    'Wikimedia\\Assert\\Test\\' => array($vendorDir . '/wikimedia/assert/tests/phpunit'),
    'Wikimedia\\Assert\\' => array($vendorDir . '/wikimedia/assert/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
