<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/pear/console_getopt',
    $vendorDir . '/pear/mail',
    $vendorDir . '/pear/mail_mime',
    $vendorDir . '/pear/net_smtp',
    $vendorDir . '/pear/net_socket',
    $vendorDir . '/pear/net_url2',
    $vendorDir . '/pear/pear_exception',
    $vendorDir . '/pear/pear-core-minimal/src',
);
