<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'reference' => '48cc5e659cc5dbe2cb5c80a75f9fe86e83b7c234',
        'name' => '__root__',
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'reference' => '48cc5e659cc5dbe2cb5c80a75f9fe86e83b7c234',
            'dev_requirement' => false,
        ),
        'beberlei/assert' => array(
            'pretty_version' => 'v3.3.0',
            'version' => '3.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'reference' => '5367e3895976b49704ae671f75bc5f0ba1b986ab',
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.8.17',
            'version' => '0.8.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'reference' => 'e6f8e7d04346a95be89580f8c2c22d6c3fa65556',
            'dev_requirement' => false,
        ),
        'christian-riesen/base32' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../christian-riesen/base32',
            'aliases' => array(),
            'reference' => '5777d962c9f55385eefd078a1bf623ce04a4f6ca',
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.2.10',
            'version' => '1.2.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => '9fdb22c2e97a614657716178093cd1da90a64aa8',
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.2.5',
            'version' => '3.2.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '31f3ea725711245195f62e54ffa402d8ef2fdba9',
            'dev_requirement' => false,
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'reference' => 'de7483c0805750a6462b372eab55d022d555df02',
            'dev_requirement' => false,
        ),
        'data-values/common' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/common',
            'aliases' => array(),
            'reference' => '315bd95ef8e5c360ce8a1cf02c0eef35bbb92561',
            'dev_requirement' => false,
        ),
        'data-values/data-values' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/data-values',
            'aliases' => array(),
            'reference' => '63dee286f8bb4ae7899c2d2e8d439e7b5332cc49',
            'dev_requirement' => false,
        ),
        'data-values/geo' => array(
            'pretty_version' => '4.2.3',
            'version' => '4.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/geo',
            'aliases' => array(),
            'reference' => 'a08d5ce38c2cb789ff8942e9082ce04dfc55a850',
            'dev_requirement' => false,
        ),
        'data-values/interfaces' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/interfaces',
            'aliases' => array(),
            'reference' => '244d078954bc05edf8f8c6b088e848289171c3a8',
            'dev_requirement' => false,
        ),
        'data-values/number' => array(
            'pretty_version' => '0.11.1',
            'version' => '0.11.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/number',
            'aliases' => array(),
            'reference' => '3177a4e11fee862d59a4f66c6b35408e9c609843',
            'dev_requirement' => false,
        ),
        'data-values/serialization' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/serialization',
            'aliases' => array(),
            'reference' => '5bc3640f7ddb642479ff490fae64fcf19c7e75af',
            'dev_requirement' => false,
        ),
        'data-values/time' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/time',
            'aliases' => array(),
            'reference' => 'abbb585f2c71ca8a1ac9aea858cf5ba6b8920320',
            'dev_requirement' => false,
        ),
        'defuse/php-encryption' => array(
            'pretty_version' => 'v2.2.1',
            'version' => '2.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../defuse/php-encryption',
            'aliases' => array(),
            'reference' => '0f407c43b953d571421e0020ba92082ed5fb7620',
            'dev_requirement' => false,
        ),
        'diff/diff' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../diff/diff',
            'aliases' => array(),
            'reference' => '89bbd224a9ad6cc6cb8e01263ae5add2564e7cf0',
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'reference' => '0c93d0e5b852634159d9f349b1848acde845400b',
            'dev_requirement' => false,
        ),
        'fgrosse/phpasn1' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fgrosse/phpasn1',
            'aliases' => array(),
            'reference' => '7ebf2a09084a7bbdb7b879c66fdf7ad80461bbe8',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.2.0',
            'version' => '5.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'feb0e820b8436873675fd3aca04f3728eb2185cb',
            'dev_requirement' => false,
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'reference' => 'd01be5894a5c1a3381c58c9b1795cd07f96c30f7',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.2.0',
            'version' => '7.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '0aa74dfb41ae110835923ef10a9d803a22d50e79',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '60d379c243457e073cff02bc323a2a86cb355631',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '53330f47520498c0ae1f61f7e2c90f55690c06a3',
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/ringphp',
            'aliases' => array(),
            'reference' => '5e2a174052995663dd68e6b5ad838afd47dd615b',
            'dev_requirement' => false,
        ),
        'guzzlehttp/streams' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/streams',
            'aliases' => array(),
            'reference' => '47aaa48e27dae43d39fc1cea0ccf0d84ac1a2ba5',
            'dev_requirement' => false,
        ),
        'jakobo/hotp-php' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakobo/hotp-php',
            'aliases' => array(),
            'reference' => 'ff2f13d1918001e54b3f49deb1d366bcfcc98437',
            'dev_requirement' => false,
        ),
        'james-heinrich/getid3' => array(
            'pretty_version' => 'v1.9.21',
            'version' => '1.9.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../james-heinrich/getid3',
            'aliases' => array(),
            'reference' => '36f5dabb1325415a4b07a401113f8db2eb81eca1',
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.11',
            'version' => '5.2.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'reference' => '2ab6744b7296ded80f8cc4f9509abbff393399aa',
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '3.4.6',
            'version' => '3.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'reference' => '3ef8657a78278dfeae7707d51747251db4176240',
            'dev_requirement' => false,
        ),
        'league/event' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/event',
            'aliases' => array(),
            'reference' => 'd2cc124cf9a3fab2bb4ff963307f60361ce4d119',
            'dev_requirement' => false,
        ),
        'league/oauth2-server' => array(
            'pretty_version' => 'dev-v9.0.0-alpha',
            'version' => 'dev-v9.0.0-alpha',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-server',
            'aliases' => array(
                0 => '9999999-dev',
                1 => '9.0.0',
            ),
            'reference' => '61d770dc284898ea2905d66e12f8f7e5f6664092',
            'dev_requirement' => false,
        ),
        'league/oauth2server' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'league/uri' => array(
            'pretty_version' => '6.4.0',
            'version' => '6.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri',
            'aliases' => array(),
            'reference' => '09da64118eaf4c5d52f9923a1e6a5be1da52fd9a',
            'dev_requirement' => false,
        ),
        'league/uri-components' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri-components',
            'aliases' => array(),
            'reference' => '14bab20b05bc20d16dec17401a9027c679412589',
            'dev_requirement' => false,
        ),
        'league/uri-interfaces' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri-interfaces',
            'aliases' => array(),
            'reference' => '00e7e2943f76d8cb50c7dfdc2f6dee356e15e383',
            'dev_requirement' => false,
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'dev_requirement' => false,
        ),
        'lncd/oauth2' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.10.1',
            'version' => '1.10.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'reference' => '569bd44d97d30a4ec12c7793a33004a76d4caf18',
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.8.1',
            'version' => '0.8.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'reference' => '32f274051c543fc865e5a84d3a2c703913641ea8',
            'dev_requirement' => false,
        ),
        'mediawiki/data-values' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '1cb1cde8e8dd0f70cc0fe51354a59acad9302084',
            'dev_requirement' => false,
        ),
        'mustangostang/spyc' => array(
            'pretty_version' => '0.6.3',
            'version' => '0.6.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mustangostang/spyc',
            'aliases' => array(),
            'reference' => '4627c838b16550b666d15aeae1e5289dd5b77da0',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.13.0',
            'version' => '4.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '50953a2691a922aa1769461637869a0a2faa3f53',
            'dev_requirement' => false,
        ),
        'nmred/kafka-php' => array(
            'pretty_version' => 'v0.1.5',
            'version' => '0.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nmred/kafka-php',
            'aliases' => array(),
            'reference' => '317ad8c208684db8b9e6d2f5bf7f471e89a8b4eb',
            'dev_requirement' => false,
        ),
        'onoi/message-reporter' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/message-reporter',
            'aliases' => array(),
            'reference' => 'cdc7f2c666cef581a1a1e31c62d5a6f2d8ba1482',
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.42.0',
            'version' => '0.42.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'reference' => 'cf3761126c1da853bc7fd127e8471e5bfdde911e',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.99.99',
            ),
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'reference' => '9609ed5e42ac5b221dfd9af85de005c59d418ee7',
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.11',
            'version' => '1.10.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'reference' => 'd4fb9ce61201593d0f8c6db629c45e29c3409c14',
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'reference' => '51e5997b711fbd1e5a9a075634d4d682168537fa',
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.11',
            'version' => '1.10.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'reference' => '68d0d32ada737153b7e93b8d3c710ebe70ac867d',
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'reference' => '86406047271859ffc13424a048541f4531f53601',
            'dev_requirement' => false,
        ),
        'pleonasm/bloom-filter' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pleonasm/bloom-filter',
            'aliases' => array(),
            'reference' => '4a3292c9f83a778c44271bf4e4f6be1204b87f7b',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.8',
            'version' => '0.10.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'reference' => 'e4573f47750dd6c92dca5aee543fa77513cbd8d3',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'reference' => 'ab2237657ad99667a5143e32ba2683c8029563d4',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.2.3',
            'version' => '4.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df',
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.8.0',
            'version' => '2.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => 'f3cff96a19736714524ca0dd1d4130de73dbbbc4',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.2.3',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.11',
            ),
        ),
        'ruflin/elastica' => array(
            'pretty_version' => '6.2.0',
            'version' => '6.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ruflin/elastica',
            'aliases' => array(),
            'reference' => '6ef9cb6c01e0c167d31b424cb1f768ecc4ef9565',
            'dev_requirement' => false,
        ),
        'serialization/serialization' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serialization/serialization',
            'aliases' => array(),
            'reference' => '6fa293415e2b70c30c1e673d8bcd04d27dc15e44',
            'dev_requirement' => false,
        ),
        'spomky-labs/base64url' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/base64url',
            'aliases' => array(),
            'reference' => '7752ce931ec285da4ed1f4c5aa27e45e097be61d',
            'dev_requirement' => false,
        ),
        'spomky-labs/cbor-php' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/cbor-php',
            'aliases' => array(),
            'reference' => 'b8e51e6a13606ab1dd8a64aa295651d8ad57ccd1',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '8b1008344647462ae6ec57559da166c2bfa5e16a',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v4.4.31',
            'version' => '4.4.31.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => '43ede438d4cb52cd589ae5dc070e9323866ba8e0',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '5f38c8804a9e97d23e0c8d63341088cd8a22d627',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.1',
            ),
        ),
        'symfony/polyfill-intl-idn' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.0',
            ),
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.1',
            ),
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.12.0',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'fba8933c384d6476ab14fb7b8526e5287ca7e010',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '1100343ed1a92e3a38f9ae122fc0eb21602547be',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '38f26c7d6ed535217ea393e05634cb0b244a1967',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'f040a30e04b57fbcc9c6cbcf4dbaa96bd318b9bb',
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'reference' => '8d224396e28d30f81969f083a58763b8b9ceb0a5',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v5.3.9',
            'version' => '5.3.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => '6e69f3551c1a3356cf6ea8d019bf039a0f8b6886',
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '95c812666f3e91db75385749fe219c5e494c7f95',
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v5.3.8',
            'version' => '5.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'reference' => '3a773f6f03ef2846c280e4f5b5f34cf950ead127',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.3.8',
            'version' => '5.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => 'eaaea4098be1c90c8285543e1356a09c8aa5c8da',
            'dev_requirement' => false,
        ),
        'thecodingmachine/safe' => array(
            'pretty_version' => 'v1.3.3',
            'version' => '1.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../thecodingmachine/safe',
            'aliases' => array(),
            'reference' => 'a8ab0876305a4cdaef31b2350fcb9811b5608dbc',
            'dev_requirement' => false,
        ),
        'web-auth/cose-lib' => array(
            'pretty_version' => 'v3.3.9',
            'version' => '3.3.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-auth/cose-lib',
            'aliases' => array(),
            'reference' => 'ed172d2dc1a6b87b5c644c07c118cd30c1b3819b',
            'dev_requirement' => false,
        ),
        'web-auth/metadata-service' => array(
            'pretty_version' => 'v3.3.9',
            'version' => '3.3.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-auth/metadata-service',
            'aliases' => array(),
            'reference' => '8488d3a832a38cc81c670fce05de1e515c6e64b1',
            'dev_requirement' => false,
        ),
        'web-auth/webauthn-lib' => array(
            'pretty_version' => 'v3.3.9',
            'version' => '3.3.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-auth/webauthn-lib',
            'aliases' => array(),
            'reference' => '04b98ee3d39cb79dad68a7c15c297c085bf66bfe',
            'dev_requirement' => false,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'reference' => 'd8e97f15b8f3d3799899e3d56452d34511be5764',
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'reference' => 'e8ebaa7bb7c8a8395481a05f6dc4deaceab11c33',
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'reference' => '449f0d0237cf1e0e71faec90680c88d4af6e711d',
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'reference' => 'd49d96232f045311dc1f21bf0d7e40adf82a1f1d',
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'reference' => '83d78cb8018d5c0f66fd6d0efff6a8ae2de92d36',
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => 'v0.3.0',
            'version' => '0.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'reference' => '5b51a88a27e17f485ba1295ee6916620686cd5a5',
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'dev_requirement' => false,
        ),
        'wikimedia/css-sanitizer' => array(
            'pretty_version' => 'v3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/css-sanitizer',
            'aliases' => array(),
            'reference' => '718e2a79fc3fec4c7a43193b5e2ac3bae6756ee4',
            'dev_requirement' => false,
        ),
        'wikimedia/dodo' => array(
            'pretty_version' => 'v0.3.0',
            'version' => '0.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/dodo',
            'aliases' => array(),
            'reference' => 'e46b9c8a1e5804509d39d03d612f02c15fed0759',
            'dev_requirement' => false,
        ),
        'wikimedia/equivset' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/equivset',
            'aliases' => array(),
            'reference' => 'f41a259526a5597e1c3cb3cf745d1f1af6d36a00',
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'reference' => 'f18622f3384b9b7fed185bff2a46594aec92fa47',
            'dev_requirement' => false,
        ),
        'wikimedia/idle-dom' => array(
            'pretty_version' => 'v0.10.0',
            'version' => '0.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/idle-dom',
            'aliases' => array(),
            'reference' => '1d34b55cfe259fd26c541811581c2e1578b46727',
            'dev_requirement' => false,
        ),
        'wikimedia/ip-set' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-set',
            'aliases' => array(),
            'reference' => '4efe81f0ffb907a60778a72faf6ede17bb490081',
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'reference' => 'ba5db9991418c9b00c4ef7d327c32bf595755d02',
            'dev_requirement' => false,
        ),
        'wikimedia/langconv' => array(
            'pretty_version' => '0.4.2',
            'version' => '0.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/langconv',
            'aliases' => array(),
            'reference' => '4bd255fd316df6650c489fa0f9b621c48458859b',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'dev_requirement' => false,
        ),
        'wikimedia/lucene-explain-parser' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/lucene-explain-parser',
            'aliases' => array(),
            'reference' => '5ff5511ce6163fa6c5ff770b79306334c31bd679',
            'dev_requirement' => false,
        ),
        'wikimedia/minify' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/minify',
            'aliases' => array(),
            'reference' => '2efef5f0b97d6342504490cd2525d2bc6eb8821e',
            'dev_requirement' => false,
        ),
        'wikimedia/normalized-exception' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/normalized-exception',
            'aliases' => array(),
            'reference' => 'ed9fc13d75f65c80dc1a95d4792658c97fd782e6',
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'reference' => 'fcfc7a0dafe9608231816d6bf74919826d9bc885',
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.15.0-a3',
            'version' => '0.15.0.0-alpha3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'reference' => 'da1ff898afb747ce363ac87e225784b56694ff88',
            'dev_requirement' => false,
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'reference' => '99e7e926f1b61f71623d517fe38d9eec8618c59d',
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'reference' => '8f106f38ff811906853511a934d7f5e86dce3d20',
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'reference' => 'b237d203c820cd1000f2c5ecad25de9fa7165612',
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'reference' => 'd46adaad8c6640eb6ba834b6268188ff0426c449',
            'dev_requirement' => false,
        ),
        'wikimedia/request-timeout' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/request-timeout',
            'aliases' => array(),
            'reference' => '8828e701fbc4e6090e3a5baac2ffc14730f099ad',
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'reference' => '60eebada7cc64b7073d90e7d4bab00efaafa0ba9',
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'reference' => '0a480d9a9772634697c77598726cf24606597bd0',
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'reference' => '5ef69a8a8b0d2ea115d08469bdab468f58fac820',
            'dev_requirement' => false,
        ),
        'wikimedia/shellbox' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/shellbox',
            'aliases' => array(),
            'reference' => 'a51b66b14332bf3e3ff80578d6564441eaf5b288',
            'dev_requirement' => false,
        ),
        'wikimedia/testing-access-wrapper' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/testing-access-wrapper',
            'aliases' => array(),
            'reference' => '280e613c76f481f2fe90e0ea22361080b6ab0d65',
            'dev_requirement' => false,
        ),
        'wikimedia/textcat' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/textcat',
            'aliases' => array(),
            'reference' => '4f13aed2b32382c9d2fe9dc8b3e3fbb26ea4a2a9',
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'reference' => '42ce5586d2189826e28ebcf4cedc96226b6d77e2',
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'reference' => 'e690d29487a6ee346bcf4cbf5a6fd89170fa2306',
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'reference' => '9bb0894e8c5195d43b2f2babbe4cc8f36bd5be0e',
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'reference' => '9a92384ae11e1a3b7ecfe0feef1809b1af73889b',
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'reference' => '11b01a2286fd377cb15c2f5561e10f56d58f37a9',
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.8.1',
            'version' => '0.8.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'reference' => '4fc577e28e09eec165b64ed74ce878ba4ea45a35',
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'reference' => 'ab537a887f393ca8e759638aadc675f01f8859a1',
            'dev_requirement' => false,
        ),
        'wmde/php-vuejs-templating' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wmde/php-vuejs-templating',
            'aliases' => array(),
            'reference' => 'f0c35ef0875d05fe74c9a0e0361b888e5c6818d0',
            'dev_requirement' => false,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.6',
            'version' => '1.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'reference' => 'b451f73e8b5c73e62e365997ba3c993a0376b72a',
            'dev_requirement' => false,
        ),
    ),
);
