<?php return array(
    'root' => array(
        'name' => 'mediawiki/core',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '299bfd7b408a7143abd5915f86b2c3489eeddc11',
        'type' => 'mediawiki-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'addshore/psr-6-mediawiki-bagostuff-adapter' => array(
            'pretty_version' => '0.1',
            'version' => '0.1.0.0',
            'reference' => '92f3bb69bf3e7f51b8b66ae74b6a4a291637354c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../addshore/psr-6-mediawiki-bagostuff-adapter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'amzn/login-and-pay-with-amazon-sdk-php' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '0c923fe9926621bb8a39a22cecd1d2f33c75de30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amzn/login-and-pay-with-amazon-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clio/clio' => array(
            'pretty_version' => '0.1.8',
            'version' => '0.1.8.0',
            'reference' => '6a9f600b73fa213e817d5c1e67a4641aecd156ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clio/clio',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'coderkungfu/php-queue' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'cd29afd03a5b4b740ce6c50128f1e69723c54f72',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coderkungfu/php-queue',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.4',
            'version' => '1.3.4.0',
            'reference' => '69098eca243998b53eed7a48d82dedd28b447cd5',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => 'c29dc4b93137acb82734f672c37e029dfbd95b35',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'corneltek/getoptionkit' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => '8f79aa38a90f1c0e66e712ed72fbc259130e6be9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../corneltek/getoptionkit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'befd1eb7b1e70ee2cd71cd5b9a86ff250d2e8423',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.13.0',
            'version' => '2.13.0.0',
            'reference' => '6a41d8fbd6b90052bc34dff3b4252d0f88067b23',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.5',
            'version' => '7.4.5.0',
            'reference' => '1dd98b0564cb3f6bd16ce683cb755f94c10fbd82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'b635f279edd83fc275f822a1188157ffea568ff6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.11',
            'version' => '5.2.11.0',
            'reference' => '2ab6744b7296ded80f8cc4f9509abbff393399aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.11.0',
            'version' => '1.11.0.0',
            'reference' => 'b1f3c0699525336d09cc5161a2861268d9f2ae5b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind/minfraud' => array(
            'pretty_version' => 'v1.22.0',
            'version' => '1.22.0.0',
            'reference' => '1e13ba7569697f1de3afef812c09e068f727adf7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/minfraud',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.9.0',
            'version' => '0.9.0.0',
            'reference' => '4dc5a3e8df38aea4ca3b1096cee3a038094e9b53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '299bfd7b408a7143abd5915f86b2c3489eeddc11',
            'type' => 'mediawiki-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/mediawiki' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.39.5',
            ),
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1cb1cde8e8dd0f70cc0fe51354a59acad9302084',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'c1fbe70bfb5ad41b8ec5785056b0e308b40d4831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.44.5',
            'version' => '0.44.5.0',
            'reference' => '49dffe151f28aa1556adca063d4faa82b2634822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'reference' => '1665e1b1dc0261a15cb3ee99ef38b4254aa7564a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.11',
            'version' => '1.10.11.0',
            'reference' => 'd4fb9ce61201593d0f8c6db629c45e29c3409c14',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '51e5997b711fbd1e5a9a075634d4d682168537fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.11',
            'version' => '1.10.11.0',
            'reference' => '68d0d32ada737153b7e93b8d3c710ebe70ac867d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.7.1',
            'version' => '6.7.1.0',
            'reference' => '49cd7ea3d2563f028d7811f06864a53b1f15ff55',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pleonasm/bloom-filter' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '57c8cf69148fea2327dcf96b21ce50df7ede1dfc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pleonasm/bloom-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v1.1.10',
            'version' => '1.1.10.0',
            'reference' => 'a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'respect/stringifier' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => 'e55af3c8aeaeaa2abb5fa47a58a8e9688cc23b59',
            'type' => 'library',
            'install_path' => __DIR__ . '/../respect/stringifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'respect/validation' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'reference' => '4c21a7ffc9a4915673cb2c2843963919e664e627',
            'type' => 'library',
            'install_path' => __DIR__ . '/../respect/validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.11',
            ),
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'reference' => '3929d9fe8148d17819ad0178c748b8d339420709',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php54' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '37285b1d5d13f37c8bee546d8d2ad0353460c4c7',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php55' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => 'c17452124a883900e1d73961f9075a638399c1a0',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => 'cfa0ae98841b9e461207c13ab093d76b0fa7bace',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.10',
            'version' => '5.4.10.0',
            'reference' => '04e42926429d9e8b39c174387ab990bf7817f7a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v1.44.7',
            'version' => '1.44.7.0',
            'reference' => '0887422319889e442458e48e2f3d9add1a172ad5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'whichbrowser/parser' => array(
            'pretty_version' => 'v2.1.7',
            'version' => '2.1.7.0',
            'reference' => '1044880bc792dbce5948fbff22ae731c43c280d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../whichbrowser/parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.1',
            'version' => '0.5.1.0',
            'reference' => '27c983fddac1197dc37f6a7cec00fc02861529cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'e8ebaa7bb7c8a8395481a05f6dc4deaceab11c33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'aa997185e0b42c1f61a11f3e1980cad144175111',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '70c724f88faa74338c9918f5b999445a615593e8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '83d78cb8018d5c0f66fd6d0efff6a8ae2de92d36',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => 'v0.4.0',
            'version' => '0.4.0.0',
            'reference' => 'e16d64009724401d8ab870724322b88d11baa75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '4.0.3',
            'version' => '4.0.3.0',
            'reference' => '9f3f30ad5d0287a1ca17c50bcbc45457db534208',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/idle-dom' => array(
            'pretty_version' => 'v0.10.0',
            'version' => '0.10.0.0',
            'reference' => '1d34b55cfe259fd26c541811581c2e1578b46727',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/idle-dom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-set' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '9650ba486e21a84659fcfd46b3e5f2c4fa2b735c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-set',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'f52a68b95fd3aac91cde3bdbc8654e2faa2fba38',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/minify' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '61b35567bb3fb85c1086f30809cc67d5900c591f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/normalized-exception' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'ed9fc13d75f65c80dc1a95d4792658c97fd782e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/normalized-exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '20d19657cfbedb1e7bd61c6696e8a16ade232e5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.16.1',
            'version' => '0.16.1.0',
            'reference' => '02ad1ede5131d7129f4798ff34c9836c94709743',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '40c9761329415ada958688d43ba4b8a447aa3037',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'reference' => '8f106f38ff811906853511a934d7f5e86dce3d20',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'b237d203c820cd1000f2c5ecad25de9fa7165612',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '0997340924fb60a15590fc5001b6091c24fef1a3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/request-timeout' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'e306a7cb1fb3a1ca3ce93992c56efb62b537c4bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/request-timeout',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '0aa66cf58f98ca2de9972a8177cbec625c4c9969',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'dd522a6cfb4c0180b0a39d12fc57046a347c4d81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c63d949c363378a5f435cfd7a81932aa6f712462',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/shellbox' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '6b5abcd4a467b27b5ba4fc28f7730ea5d01367a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/shellbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/smash-pig' => array(
            'pretty_version' => 'v0.8.9.4',
            'version' => '0.8.9.4',
            'reference' => '31e95e068c4d6582da546f328688b8c81a011082',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/smash-pig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '03248b0ac204b1cc8ace011e7ad3680bdef0eb8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'e690d29487a6ee346bcf4cbf5a6fd89170fa2306',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '9bb0894e8c5195d43b2f2babbe4cc8f36bd5be0e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'reference' => '9a92384ae11e1a3b7ecfe0feef1809b1af73889b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v4.0.1',
            'version' => '4.0.1.0',
            'reference' => '0d526868d92fa855c70a845336a777c63b30b400',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.8.6',
            'version' => '0.8.6.0',
            'reference' => 'f2bc581314de73858d33c80c705da9b5644a996a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '423c867462801fda08a1c31009ec19d91a68b410',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.6',
            'version' => '1.2.6.0',
            'reference' => 'b451f73e8b5c73e62e365997ba3c993a0376b72a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
