# Settings for astropay (d*local api version 1)
#
# To override, create a file in:
#   /etc/smashpig/astropay/main.yaml
#   $HOME/.smashpig/astropay/main.yaml

logging:
    root-context: SmashPig-AstroPay

actions:
    - SmashPig\Core\Actions\IncomingMessage

endpoints:
    listener:
        class: SmashPig\PaymentProviders\AstroPay\AstroPayListener

login: createlogin
secret: "secretkey"
charset: iso-8859-1
